export const TRANSLATIONS_MODEL_WORKER_EVENT = 'translationsModelWorkerEvent';
export const TRANSLATIONS_TRANSLATION_WORKER_EVENT =
  'translationsModelTranslationEvent';

export const SPEECHRECOGNITION_MODEL_WORKER_EVENT =
  'speechrecognitionModelWorkerEvent';
export const SPEECHRECOGNITION_TRANSCRIBE_WORKER_EVENT =
  'speechrecognitionModelTranscribeEvent';

export const FLORES_200_CODES = {
  ace_Arab: 'Acehnese (Arabic script)',
  ace_Latn: 'Acehnese (Latin script)',
  acm_Arab: 'Mesopotamian Arabic',
  acq_Arab: 'Ta’izzi-Adeni Arabic',
  aeb_Arab: 'Tunisian Arabic',
  afr_Latn: 'Afrikaans',
  ajp_Arab: 'South Levantine Arabic',
  aka_Latn: 'Akan',
  amh_Ethi: 'Amharic',
  apc_Arab: 'North Levantine Arabic',
  arb_Arab: 'Modern Standard Arabic',
  arb_Latn: 'Modern Standard Arabic (Romanized)',
  ars_Arab: 'Najdi Arabic',
  ary_Arab: 'Moroccan Arabic',
  arz_Arab: 'Egyptian Arabic',
  asm_Beng: 'Assamese',
  ast_Latn: 'Asturian',
  awa_Deva: 'Awadhi',
  ayr_Latn: 'Central Aymara',
  azb_Arab: 'South Azerbaijani',
  azj_Latn: 'North Azerbaijani',
  bak_Cyrl: 'Bashkir',
  bam_Latn: 'Bambara',
  ban_Latn: 'Balinese',
  bel_Cyrl: 'Belarusian',
  bem_Latn: 'Bemba',
  ben_Beng: 'Bengali',
  bho_Deva: 'Bhojpuri',
  bjn_Arab: 'Banjar (Arabic script)',
  bjn_Latn: 'Banjar (Latin script)',
  bod_Tibt: 'Standard Tibetan',
  bos_Latn: 'Bosnian',
  bug_Latn: 'Buginese',
  bul_Cyrl: 'Bulgarian',
  cat_Latn: 'Catalan',
  ceb_Latn: 'Cebuano',
  ces_Latn: 'Czech',
  cjk_Latn: 'Chokwe',
  ckb_Arab: 'Central Kurdish',
  crh_Latn: 'Crimean Tatar',
  cym_Latn: 'Welsh',
  dan_Latn: 'Danish',
  deu_Latn: 'German',
  dik_Latn: 'Southwestern Dinka',
  dyu_Latn: 'Dyula',
  dzo_Tibt: 'Dzongkha',
  ell_Grek: 'Greek',
  eng_Latn: 'English',
  epo_Latn: 'Esperanto',
  est_Latn: 'Estonian',
  eus_Latn: 'Basque',
  ewe_Latn: 'Ewe',
  fao_Latn: 'Faroese',
  fij_Latn: 'Fijian',
  fin_Latn: 'Finnish',
  fon_Latn: 'Fon',
  fra_Latn: 'French',
  fur_Latn: 'Friulian',
  fuv_Latn: 'Nigerian Fulfulde',
  gla_Latn: 'Scottish Gaelic',
  gle_Latn: 'Irish',
  glg_Latn: 'Galician',
  grn_Latn: 'Guarani',
  guj_Gujr: 'Gujarati',
  hat_Latn: 'Haitian Creole',
  hau_Latn: 'Hausa',
  heb_Hebr: 'Hebrew',
  hin_Deva: 'Hindi',
  hne_Deva: 'Chhattisgarhi',
  hrv_Latn: 'Croatian',
  hun_Latn: 'Hungarian',
  hye_Armn: 'Armenian',
  ibo_Latn: 'Igbo',
  ilo_Latn: 'Ilocano',
  ind_Latn: 'Indonesian',
  isl_Latn: 'Icelandic',
  ita_Latn: 'Italian',
  jav_Latn: 'Javanese',
  jpn_Jpan: 'Japanese',
  kab_Latn: 'Kabyle',
  kac_Latn: 'Jingpho',
  kam_Latn: 'Kamba',
  kan_Knda: 'Kannada',
  kas_Arab: 'Kashmiri (Arabic script)',
  kas_Deva: 'Kashmiri (Devanagari script)',
  kat_Geor: 'Georgian',
  knc_Arab: 'Central Kanuri (Arabic script)',
  knc_Latn: 'Central Kanuri (Latin script)',
  kaz_Cyrl: 'Kazakh',
  kbp_Latn: 'Kabiyè',
  kea_Latn: 'Kabuverdianu',
  khm_Khmr: 'Khmer',
  kik_Latn: 'Kikuyu',
  kin_Latn: 'Kinyarwanda',
  kir_Cyrl: 'Kyrgyz',
  kmb_Latn: 'Kimbundu',
  kmr_Latn: 'Northern Kurdish',
  kon_Latn: 'Kikongo',
  kor_Hang: 'Korean',
  lao_Laoo: 'Lao',
  lij_Latn: 'Ligurian',
  lim_Latn: 'Limburgish',
  lin_Latn: 'Lingala',
  lit_Latn: 'Lithuanian',
  lmo_Latn: 'Lombard',
  ltg_Latn: 'Latgalian',
  ltz_Latn: 'Luxembourgish',
  lua_Latn: 'Luba-Kasai',
  lug_Latn: 'Ganda',
  luo_Latn: 'Luo',
  lus_Latn: 'Mizo',
  lvs_Latn: 'Standard Latvian',
  mag_Deva: 'Magahi',
  mai_Deva: 'Maithili',
  mal_Mlym: 'Malayalam',
  mar_Deva: 'Marathi',
  min_Arab: 'Minangkabau (Arabic script)',
  min_Latn: 'Minangkabau (Latin script)',
  mkd_Cyrl: 'Macedonian',
  plt_Latn: 'Plateau Malagasy',
  mlt_Latn: 'Maltese',
  mni_Beng: 'Meitei (Bengali script)',
  khk_Cyrl: 'Halh Mongolian',
  mos_Latn: 'Mossi',
  mri_Latn: 'Maori',
  mya_Mymr: 'Burmese',
  nld_Latn: 'Dutch',
  nno_Latn: 'Norwegian Nynorsk',
  nob_Latn: 'Norwegian Bokmål',
  npi_Deva: 'Nepali',
  nso_Latn: 'Northern Sotho',
  nus_Latn: 'Nuer',
  nya_Latn: 'Nyanja',
  oci_Latn: 'Occitan',
  gaz_Latn: 'West Central Oromo',
  ory_Orya: 'Odia',
  pag_Latn: 'Pangasinan',
  pan_Guru: 'Eastern Panjabi',
  pap_Latn: 'Papiamento',
  pes_Arab: 'Western Persian',
  pol_Latn: 'Polish',
  por_Latn: 'Portuguese',
  prs_Arab: 'Dari',
  pbt_Arab: 'Southern Pashto',
  quy_Latn: 'Ayacucho Quechua',
  ron_Latn: 'Romanian',
  run_Latn: 'Rundi',
  rus_Cyrl: 'Russian',
  sag_Latn: 'Sango',
  san_Deva: 'Sanskrit',
  sat_Olck: 'Santali',
  scn_Latn: 'Sicilian',
  shn_Mymr: 'Shan',
  sin_Sinh: 'Sinhala',
  slk_Latn: 'Slovak',
  slv_Latn: 'Slovenian',
  smo_Latn: 'Samoan',
  sna_Latn: 'Shona',
  snd_Arab: 'Sindhi',
  som_Latn: 'Somali',
  sot_Latn: 'Southern Sotho',
  spa_Latn: 'Spanish',
  als_Latn: 'Tosk Albanian',
  srd_Latn: 'Sardinian',
  srp_Cyrl: 'Serbian',
  ssw_Latn: 'Swati',
  sun_Latn: 'Sundanese',
  swe_Latn: 'Swedish',
  swh_Latn: 'Swahili',
  szl_Latn: 'Silesian',
  tam_Taml: 'Tamil',
  tat_Cyrl: 'Tatar',
  tel_Telu: 'Telugu',
  tgk_Cyrl: 'Tajik',
  tgl_Latn: 'Tagalog',
  tha_Thai: 'Thai',
  tir_Ethi: 'Tigrinya',
  taq_Latn: 'Tamasheq (Latin script)',
  taq_Tfng: 'Tamasheq (Tifinagh script)',
  tpi_Latn: 'Tok Pisin',
  tsn_Latn: 'Tswana',
  tso_Latn: 'Tsonga',
  tuk_Latn: 'Turkmen',
  tum_Latn: 'Tumbuka',
  tur_Latn: 'Turkish',
  twi_Latn: 'Twi',
  tzm_Tfng: 'Central Atlas Tamazight',
  uig_Arab: 'Uyghur',
  ukr_Cyrl: 'Ukrainian',
  umb_Latn: 'Umbundu',
  urd_Arab: 'Urdu',
  uzn_Latn: 'Northern Uzbek',
  vec_Latn: 'Venetian',
  vie_Latn: 'Vietnamese',
  war_Latn: 'Waray',
  wol_Latn: 'Wolof',
  xho_Latn: 'Xhosa',
  ydd_Hebr: 'Eastern Yiddish',
  yor_Latn: 'Yoruba',
  yue_Hant: 'Yue Chinese',
  zho_Hans: 'Chinese (Simplified)',
  zho_Hant: 'Chinese (Traditional)',
  zsm_Latn: 'Standard Malay',
  zul_Latn: 'Zulu',
};

export const M2M100_LANGUAGES = {
  af: 'Afrikaans',
  am: 'Amharic',
  ar: 'Arabic',
  ast: 'Asturian',
  az: 'Azerbaijani',
  ba: 'Bashkir',
  be: 'Belarusian',
  bg: 'Bulgarian',
  bn: 'Bengali',
  br: 'Breton',
  bs: 'Bosnian',
  ca: 'Catalan; Valencian',
  ceb: 'Cebuano',
  cs: 'Czech',
  cy: 'Welsh',
  da: 'Danish',
  de: 'German',
  el: 'Greeek',
  en: 'English',
  es: 'Spanish',
  et: 'Estonian',
  fa: 'Persian',
  ff: 'Fulah',
  fi: 'Finnish',
  fr: 'French',
  fy: 'Western Frisian',
  ga: 'Irish',
  gd: 'Gaelic; Scottish Gaelic',
  gl: 'Galician',
  gu: 'Gujarati',
  ha: 'Hausa',
  he: 'Hebrew',
  hi: 'Hindi',
  hr: 'Croatian',
  ht: 'Haitian; Haitian Creole',
  hu: 'Hungarian',
  hy: 'Armenian',
  id: 'Indonesian',
  ig: 'Igbo',
  ilo: 'Iloko',
  is: 'Icelandic',
  it: 'Italian',
  ja: 'Japanese',
  jv: 'Javanese',
  ka: 'Georgian',
  kk: 'Kazakh',
  km: 'Central Khmer',
  kn: 'Kannada',
  ko: 'Korean',
  lb: 'Luxembourgish; Letzeburgesch',
  lg: 'Ganda',
  ln: 'Lingala',
  lo: 'Lao',
  lt: 'Lithuanian',
  lv: 'Latvian',
  mg: 'Malagasy',
  mk: 'Macedonian',
  ml: 'Malayalam',
  mn: 'Mongolian',
  mr: 'Marathi',
  ms: 'Malay',
  my: 'Burmese',
  ne: 'Nepali',
  nl: 'Dutch; Flemish',
  no: 'Norwegian',
  ns: 'Northern Sotho',
  oc: 'Occitan (post 1500)',
  or: 'Oriya',
  pa: 'Panjabi; Punjabi',
  pl: 'Polish',
  ps: 'Pushto; Pashto',
  pt: 'Portuguese',
  ro: 'Romanian; Moldavian; Moldovan',
  ru: 'Russian',
  sd: 'Sindhi',
  si: 'Sinhala; Sinhalese',
  sk: 'Slovak',
  sl: 'Slovenian',
  so: 'Somali',
  sq: 'Albanian',
  sr: 'Serbian',
  ss: 'Swati',
  su: 'Sundanese',
  sv: 'Swedish',
  sw: 'Swahili',
  ta: 'Tamil',
  th: 'Thai',
  tl: 'Tagalog',
  tn: 'Tswana',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  vi: 'Vietnamese',
  wo: 'Wolof',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  zh: 'Chinese',
  zu: 'Zulu',
};

export const MBART50_LANGUAGES = {
  ar_AR: 'Arabic',
  cs_CZ: 'Czech',
  de_DE: 'German',
  en_XX: 'English',
  es_XX: 'Spanish',
  et_EE: 'Estonian',
  fi_FI: 'Finnish',
  fr_XX: 'French',
  gu_IN: 'Gujarati',
  hi_IN: 'Hindi',
  it_IT: 'Italian',
  ja_XX: 'Japanese',
  kk_KZ: 'Kazakh',
  ko_KR: 'Korean',
  lt_LT: 'Lithuanian',
  lv_LV: 'Latvian',
  my_MM: 'Burmese',
  ne_NP: 'Nepali',
  nl_XX: 'Dutch',
  ro_RO: 'Romanian',
  ru_RU: 'Russian',
  si_LK: 'Sinhala',
  tr_TR: 'Turkish',
  vi_VN: 'Vietnamese',
  zh_CN: 'Chinese',
  af_ZA: 'Afrikaans',
  az_AZ: 'Azerbaijani',
  bn_IN: 'Bengali',
  fa_IR: 'Persian',
  he_IL: 'Hebrew',
  hr_HR: 'Croatian',
  id_ID: 'Indonesian',
  ka_GE: 'Georgian',
  km_KH: 'Khmer',
  mk_MK: 'Macedonian',
  ml_IN: 'Malayalam',
  mn_MN: 'Mongolian',
  mr_IN: 'Marathi',
  pl_PL: 'Polish',
  ps_AF: 'Pashto',
  pt_XX: 'Portuguese',
  sv_SE: 'Swedish',
  sw_KE: 'Swahili',
  ta_IN: 'Tamil',
  te_IN: 'Telugu',
  th_TH: 'Thai',
  tl_XX: 'Tagalog',
  uk_UA: 'Ukrainian',
  ur_PK: 'Urdu',
  xh_ZA: 'Xhosa',
  gl_ES: 'Galician',
  sl_SI: 'Slovene',
};

export const T5_LANGUAGES_FROM = {
  en: 'English',
};

export const T5_LANGUAGES_TO = {
  fr: 'French',
  de: 'German',
  ro: 'Romanian',
};

export const TRANSCRIPTION_SOURCE_LANGUAGES = [
  { value: 'en', label: 'English' },
  { value: 'zh', label: 'Chinese' },
  { value: 'de', label: 'German' },
  { value: 'es', label: 'Spanish, Castilian' },
  { value: 'ru', label: 'Russian' },
  { value: 'ko', label: 'Korean' },
  { value: 'fr', label: 'French' },
  { value: 'ja', label: 'Japanese' },
  { value: 'pt', label: 'Portuguese' },
  { value: 'tr', label: 'Turkish' },
  { value: 'pl', label: 'Polish' },
  { value: 'ca', label: 'Catalan, Valencian' },
  { value: 'nl', label: 'Dutch, Flemish' },
  { value: 'ar', label: 'Arabic' },
  { value: 'sv', label: 'Swedish' },
  { value: 'it', label: 'Italian' },
  { value: 'id', label: 'Indonesian' },
  { value: 'hi', label: 'Hindi' },
  { value: 'fi', label: 'Finnish' },
  { value: 'vi', label: 'Vietnamese' },
  { value: 'he', label: 'Hebrew' },
  { value: 'uk', label: 'Ukrainian' },
  { value: 'el', label: 'Greek' },
  { value: 'ms', label: 'Malay' },
  { value: 'cs', label: 'Czech' },
  { value: 'ro', label: 'Romanian, Moldavian, Moldovan' },
  { value: 'da', label: 'Danish' },
  { value: 'hu', label: 'Hungarian' },
  { value: 'ta', label: 'Tamil' },
  { value: 'no', label: 'Norwegian' },
  { value: 'th', label: 'Thai' },
  { value: 'ur', label: 'Urdu' },
  { value: 'hr', label: 'Croatian' },
  { value: 'bg', label: 'Bulgarian' },
  { value: 'lt', label: 'Lithuanian' },
  { value: 'la', label: 'Latin' },
  { value: 'mi', label: 'Maori' },
  { value: 'ml', label: 'Malayalam' },
  { value: 'cy', label: 'Welsh' },
  { value: 'sk', label: 'Slovak' },
  { value: 'te', label: 'Telugu' },
  { value: 'fa', label: 'Persian' },
  { value: 'lv', label: 'Latvian' },
  { value: 'bn', label: 'Bengali' },
  { value: 'sr', label: 'Serbian' },
  { value: 'az', label: 'Azerbaijani' },
  { value: 'sl', label: 'Slovenian' },
  { value: 'kn', label: 'Kannada' },
  { value: 'et', label: 'Estonian' },
  { value: 'mk', label: 'Macedonian' },
  { value: 'br', label: 'Breton' },
  { value: 'eu', label: 'Basque' },
  { value: 'is', label: 'Icelandic' },
  { value: 'hy', label: 'Armenian' },
  { value: 'ne', label: 'Nepali' },
  { value: 'mn', label: 'Mongolian' },
  { value: 'bs', label: 'Bosnian' },
  { value: 'kk', label: 'Kazakh' },
  { value: 'sq', label: 'Albanian' },
  { value: 'sw', label: 'Swahili' },
  { value: 'gl', label: 'Galician' },
  { value: 'mr', label: 'Marathi' },
  { value: 'pa', label: 'Punjabi, Panjabi' },
  { value: 'si', label: 'Sinhala, Sinhalese' },
  { value: 'km', label: 'Khmer' },
  { value: 'sn', label: 'Shona' },
  { value: 'yo', label: 'Yoruba' },
  { value: 'so', label: 'Somali' },
  { value: 'af', label: 'Afrikaans' },
  { value: 'oc', label: 'Occitan' },
  { value: 'ka', label: 'Georgian' },
  { value: 'be', label: 'Belarusian' },
  { value: 'tg', label: 'Tajik' },
  { value: 'sd', label: 'Sindhi' },
  { value: 'gu', label: 'Gujarati' },
  { value: 'am', label: 'Amharic' },
  { value: 'yi', label: 'Yiddish' },
  { value: 'lo', label: 'Lao' },
  { value: 'uz', label: 'Uzbek' },
  { value: 'fo', label: 'Faroese' },
  { value: 'ht', label: 'Haitian Creole/Haitian' },
  { value: 'ps', label: 'Pashto/Pushto' },
  { value: 'tk', label: 'Turkmen' },
  { value: 'nn', label: 'Nynorsk' },
  { value: 'mt', label: 'Maltese' },
  { value: 'sa', label: 'Sanskrit' },
  { value: 'lb', label: 'Luxembourgish, Letzeburgesch' },
  { value: 'my', label: 'Myanmar, Burmese' },
  { value: 'bo', label: 'Tibetan' },
  { value: 'tl', label: 'Tagalog' },
  { value: 'mg', label: 'Malagasy' },
  { value: 'as', label: 'Assamese' },
  { value: 'tt', label: 'Tatar' },
  { value: 'haw', label: 'Hawaiian' },
  { value: 'ln', label: 'Lingala' },
  { value: 'ha', label: 'Hausa' },
  { value: 'ba', label: 'Bashkir' },
  { value: 'jw', label: 'Javanese' },
  { value: 'su', label: 'Sundanese' },
];
